#! /bin/sh
pkill sxhkd
sxhkd &

pgrep -x sxhkd > /dev/null || sxhkd &
mpd

#testing
#Auto init software
feh --bg-fill ~/bg/bg-forest.jpg
~/.config/polybar/launch.sh


#bspwm initial config
bspc monitor -d 1 2 3 4 5 6 7 

bspc config border_width         2
bspc config window_gap           8 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Gruvbox color borders
bspc config normal_border_color '#928374'
bspc config focused_border_color '#ffffff'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#4e4e4e'
bspc config focused_sticky_border_color '#83a598'
bspc config urgent_border_coor '#fb4934'l


#Custom apps rules
bspc rule -a Emacs state=tiled
